name: jungle_power_app
description: Jungle Power customer app (read-only) — Material3, caching, CSV export, branding.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  provider: ^6.0.5
  intl: ^0.20.2
  fl_chart:
    git:
      url: https://github.com/imaNNeoFighT/fl_chart.git
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
